export default {
    settings: "settings",
    create: "add",
    home: 'home',
    order: 'reorder-three',
    save: 'save-sharp',
    delete: 'trash-sharp',
    deleteIng: 'trash-sharp',
    deleteRec: 'trash-sharp',
    edit: 'create-outline',
    cancel: 'close',
    duplicate: 'duplicate',
    okay: 'checkmark',
    darkMode: 'contrast',
    language:'language',
    dateFormat: 'calendar',
    feedback: 'chatbubble',
    site: 'globe',
    filter: 'swap-vertical',
    ingredient: 'pie-chart',
    product: 'barcode',
    logout: 'exit',
    email: 'at-sharp',
    facebook: 'logo-facebook',
    google: 'logo-google',
    apple: 'ios-logo-apple',
    subscriptions: 'cart', //analytics-sharp, apps, bookmarks, albums
    overwriteLocal: 'cloud-download-outline', // 'arrow-down-circle-outline',
    overwriteRemote: 'cloud-upload-outline', //'arrow-up-circle-outline'
    deleteAllUserDataRemote: 'cloud-offline-outline',
    info: 'information-circle-outline',
    // info: 'information-circle'
    restore: 'refresh',
    upgrade: 'cart', // 'chevron-up-circle',
    // upgrade: 'chevron-up-circle-outline', // 'caret-up',  'arrow-up', 
    privacy: 'document-text',
    eula: 'briefcase-outline',
    analysis: 'stats-chart'  // 'analytics-outline' 'bar-chart'
}