export default {
    settings: "settings",
    create: "add",
    home: 'home',
    order: 'reorder-three',
    save: 'save-sharp',
    delete: 'trash-sharp',
    deleteIng: 'trash-sharp',
    deleteRec: 'trash-sharp',
    edit: 'create-outline',
    cancel: 'close',
    duplicate: 'duplicate',
    okay: 'checkmark',
    darkMode: 'contrast',
    language:'language',
    dateFormat: 'calendar',
    feedback: 'chatbubble',
    site: 'globe',
    filter: 'swap-vertical',
    ingredient: 'pie-chart',
    product: 'barcode',
    logout: 'exit',
    email: 'at-sharp',
    facebook: 'logo-facebook',
    google: 'logo-google',
    subscriptions: 'cart', //analytics-sharp, apps, bookmarks, albums
    overwriteLocal: 'arrow-down-circle-outline',
    overwriteRemote: 'arrow-up-circle-outline',
    info: 'information-circle-outline',
    restore: 'refresh'
    // info: 'information-circle'
}